name: zenithapp

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core & Firestore
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  
  # State Management
  provider: ^6.1.1
  
  # Persistence Local
  shared_preferences: ^2.5.3
  
  # Icons (Opcional)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true